import type { Metadata } from "next";
import { Geist, Geist_Mono ,Host_Grotesk} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import {shadcn} from '@clerk/themes'
const font = Host_Grotesk({
  subsets:['latin-ext']
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
              baseTheme: shadcn,
            }}
      >
      <body
        className={`${font.className} antialiased`}
      >
         {children}
      </body>
       </ClerkProvider>
    </html>
  );
}
